### ISSUE TITLE
Only neutral scans provided?

### ISSUE THREAD

**Issue by Shelomith** [soubhiksanyal/now_evaluation#10]
I found Validation scans only provided neutral scans for each subject.
But validation_list include all challenge: expressions, neutral, occlusions...
Can we evaluate other challenges by only neutral scans?
Is there any other way to get full scans?

**Comment by TimoBolkart** [comment]
The goal of the NoW challenge is to evaluate the accuracy of the evaluated identity face shape, and it does not evaluate the accuracy of the estimated expression. Even with a ground truth dataset with expressions, the error would be dominated by the quality of the estimated identity shape (i.e., estimating a good identity face shape but a bad expression would give a lower error than estimating a bad identity face shape with the right expression). Therefore, it is not clear how to scale that to also evaluate the reconstructed expressions.
