### ISSUE TITLE
Issues with eigen 

### ISSUE THREAD

**Issue by AyushP123** [soubhiksanyal/now_evaluation#12]
Hi,

While running make in `now_evaluation/sbody/alignment/mesh_distance` I am getting a lot of errors related to eigen. Am I supposed to use a specific version of eigen for installation?

**Comment by AyushP123** [comment]
Using 3.4.0 stable release resolves it.

**Comment by lin-girl** [comment]
Hi,Your method is very useful. Do you make mistakes like this? in python check_predictions.py <predicted_mesh_path>.
ImportError: cannot import name 'sample2meshdist' @AyushP123
