### ISSUE TITLE
command ‘usr/bin/gcc’ failed with exit code 1

### ISSUE THREAD

**Issue by Kiddo1024** [soubhiksanyal/now_evaluation#15]
你好，我在中间那步make eigen的时候，总是会报错：command ‘usr/bin/gcc’ failed with exit code 1，请问您有遇到过相同的问题吗

**Comment by Tengfei000** [comment]
> 你好，我在中间那步make eigen的时候，总是会报错：command ‘usr/bin/gcc’ failed with exit code 1，请问您有遇到过相同的问题吗

我也是 这个问题怎么解决啊

**Comment by LY-Donkey-Burger** [comment]
> > 你好，我在中间那一步make eigen的时候，总是会报错：command 'usr/bin/gcc failed with exit code 1'，请问你遇到过同样的问题吗？
> 
> 我也是这个问题怎么解决啊

Just install eigen3.2
