### ISSUE TITLE
Can not run rigid alignment completely

### ISSUE THREAD

**Issue by VictoryTianke** [soubhiksanyal/now_evaluation#16]
Thanks a lot for your great work!
I met this problem when I ran check_predictions.py：
![image](https://user-images.githubusercontent.com/73265430/172095347-de29bf02-ebac-48d7-9d6a-8b79933322dc.png)
Hope to get your help and answers！Thanks!

**Comment by VictoryTianke** [comment]
I think the program may be stuck here and can't continue to run

**Comment by TimoBolkart** [comment]
Hi, this is usually either due to errors in loading the meshes or due to wrongly labeled landmarks. Please try these steps to trace down the error: https://github.com/soubhiksanyal/now_evaluation/issues/2

**Comment by TimoBolkart** [comment]
did you manage to solve your problem?

**Comment by VictoryTianke** [comment]
Sorry for late. I solved my problem with DECA's evaluation method. Thx a lot!
