### ISSUE TITLE
expression coefficients set to zero?

### ISSUE THREAD

**Issue by wadesunyang** [soubhiksanyal/now_evaluation#17]
Thanks for releasing the code for your amazing research!

I notice that the scans only with people in neutral expressions. 

so  when i use deep3D with bfm to construct the mesh,  should i set the expression coefficients to zero?  Because the val scans only with neutral expressions, and how about the pose coefficients?

Thank you very much!

**Comment by TimoBolkart** [comment]
Yes, the NoW challenge aims at evaluating the identity face shape, therefore for evaluation, set the expression coefficients to zero. 
Before computing the error, a rigid alignment is performed between the reconstructed face and the scan, therefore the resulting error is invariant to the head pose of the reconstructed head.
