### ISSUE TITLE
what's the meaning of output?

### ISSUE THREAD

**Issue by The-crucified** [soubhiksanyal/now_evaluation#18]
when i run python check_predictions.py ./test/IMG_0045_detail.obj.obj ./test/IMG_0045.txt ./test/natural_head_rotation.000001.obj ./test/natural_head_rotation.000001_picked_points.pp
The output is 
1.56e+08 | dist: 1.56e+08 | s_reg: 0.00e+00
1.40e+08 | dist: 1.40e+08 | s_reg: 0.00e+00
1.13e+08 | dist: 1.13e+08 | s_reg: 0.00e+00
1.00e+08 | dist: 1.00e+08 | s_reg: 0.00e+00
9.64e+07 | dist: 9.64e+07 | s_reg: 0.00e+00
9.64e+07 | dist: 9.64e+07 | s_reg: 0.00e+00

what's meaning?

**Comment by TimoBolkart** [comment]
Prior to computing the error per reconstructed mesh, a rigid registration is performed to align the reconstructed face with the scan. The output you are seeing is the output of the optimizer of this rigid registration step.

**Comment by The-crucified** [comment]
> Prior to computing the error per reconstructed mesh, a rigid registration is performed to align the reconstructed face with the scan. The output you are seeing is the output of the optimizer of this rigid registration step.

thx !
When I do calculations with different reconstructed models, sometimes I get different numbers of outputs. so the output of the optimizer of this rigid registration step indicate the distance from the seven landmarks to the nearest scan points or something else?

**Comment by TimoBolkart** [comment]
The rigid registration step minimizes the distance between the scan vertices and the reconstructed mesh surface, not the distance to the seven landmarks. Depending on how good your reconstructed mesh is, this error is larger or lower.
