### ISSUE TITLE
hello，about bfm model evaluation

### ISSUE THREAD

**Issue by Luh1124** [soubhiksanyal/now_evaluation#20]
Thank you for your work，I want to test methods based on BFM model, such as 3ddfa, deepfacecon or synergynet; 
What is the index correspondence of landmarks? 
Should I set the average expression and expression coefficient to zero，and keep the influence of the rotation and translation matrices?? 
 look forward to your answers~

**Comment by TimoBolkart** [comment]
Hi, the rotation, translation, and scale of the predicted meshes have no impact on the (non-metrical) evaluation of the NoW challenge as a rigid transformation step between predicted mesh and scan prior to computing the error takes care of this. While expression has little impact on the computed error, it is favorable if the predicted meshes are of neutral expression. Therefore, setting expression parameters to zero is the way to go for BFM-based models.
