### ISSUE TITLE
The results on the NoW Challenge list calculated using test data? The results measured by the DECA validation set have a large error with the test set.

### ISSUE THREAD

**Issue by chengzihua** [soubhiksanyal/now_evaluation#22]

**Comment by TimoBolkart** [comment]
All errors reported in the [NoW Challenge list](https://now.is.tue.mpg.de/nonmetricalevaluation.html) are computed on the NoW test set. And yes, DECA reported a larger (mean) error (1.46 mm, see Section 6.3) on the NoW validation set than the (mean) error it got on the test set (1.38 mm).

**Comment by chengzihua** [comment]
I measured that the mean result of DECA on the validation set is 4.02. I am not sure what is wrong. I want to ask what method is used for this second alignment. Are all the vertices used? How the method samples from the mesh？

**Comment by chengzihua** [comment]
In the rigid alignment step, I found that gt scan and pred mesh failed to align, is there any solution? I measured that the mean of DECA on the validation set was 4.02, because some 3D models failed to align

**Comment by TimoBolkart** [comment]
There are two common issues that could lead to that, wrongly loading the meshes which can happen if one exports the meshes with vertex colors which the used mesh loader struggles with, or that the landmarks you provide with every predicted mesh are wrong. Please plot your landmarks and also the order of the landmarks on the predicted mesh to see that these are correct.
