### ISSUE TITLE
Does the head mesh affect the performance?

### ISSUE THREAD

**Issue by JiejiangWu** [soubhiksanyal/now_evaluation#24]
Hi, I am trying to evaluate the performance of some reconstruction methods in NoW. I noticed that some methods (e.g., DECA) output a complete head mesh while the GT scans only contain the face region. As I am not clear about the details of the ScanToMesh function in the code, I am not sure whether it is necessary to output only the face region mesh? Does it matter?

**Comment by TimoBolkart** [comment]
Hi, the scan-to-mesh distance computes the distance between every scan point and its closest point in the surface of the reconstructed mesh. Providing reconstructed meshes that are bigger than the cropped scans (i.e., by predicting an entire head) does not give any advantage in this evaluation measure. However, providing meshes that are smaller than the cropped scans will give a higher error. Does that answer your question?

**Comment by JiejiangWu** [comment]
Yes, thanks for the reply.
