### ISSUE TITLE
rigidly aligned error

### ISSUE THREAD

**Issue by wengjincheng** [soubhiksanyal/now_evaluation#26]
I followed the install guide and everything was correct.

In step 2, run the check_predictions.py to check the landmarks. The script could run and output the result, but the result was not correct and I think the 7 landmarks I got were right.

The method that I use to reconstruct was Deep3D pytorch. The 3DMM mode was BFM model.

I have drawn the landmarks in 2D image to compare (red points is the 7 landmarks):

![image](https://user-images.githubusercontent.com/20600119/209671890-45d00eeb-66e9-47a3-a1c4-2e1cff15cc8c.png)

![image](https://user-images.githubusercontent.com/20600119/209671513-7760aae8-32ae-4cf2-8d7f-9aa5002ba62b.png)

the result I got was not aligned:

![image](https://user-images.githubusercontent.com/20600119/209671960-60571a03-9142-4c8f-93bb-5ac60c0b63d7.png)
![image](https://user-images.githubusercontent.com/20600119/209671982-7f1dadf1-4781-4bad-82ab-7913e50e7dd7.png)
![image](https://user-images.githubusercontent.com/20600119/209672005-f77dad51-e161-4f02-b59f-6bb18ff47784.png)

And then, I ran the error compute script, I got the result distance error was too large then this method should has:
![image](https://user-images.githubusercontent.com/20600119/209672460-f045dc6c-f102-4f57-b029-bbfb5e283d8a.png)

So, I wondered if the version of scan to mesh was wrong or other things. By the way, the flame-fitting I used the master branch, and eigen I used the 3.4 version

**Comment by wengjincheng** [comment]
![image](https://user-images.githubusercontent.com/20600119/209835561-5d0137dd-8667-4879-93f8-8d187bb0792e.png)

This is the one of predicted align mesh

**Comment by wengjincheng** [comment]
I have figured it out

**Comment by TimoBolkart** [comment]
Great, thank you for the information. Can you specify what went wrong and how you fixed it in case other people are facing the same issue?

**Comment by wengjincheng** [comment]
> Great, thank you for the information. Can you specify what went wrong and how you fixed it in case other people are facing the same issue?

Yeah, I use the wrong space (not world space, I use the camera space... it's a stupid problem...) 7 3d coordinates of landmarks of predicts.
In a nutshell, I use the wrong 7 landmarks, which is why I got error results.

Thanks for your attention.
