### ISSUE TITLE
 ModuleNotFoundError: No module named 'psbody'

### ISSUE THREAD

**Issue by vinodkkurmi** [soubhiksanyal/now_evaluation#3]
Hi @soubhiksanyal 
I am geting the follwing errorr. Can you please help me in that?
  from psbody.mesh import Mesh
ModuleNotFoundError: No module named 'psbody'
Thanks

**Comment by TimoBolkart** [comment]
Hi, you must install the mesh processing libraries from [MPI-IS/mesh](https://github.com/MPI-IS/mesh) within the virtual environment.
