### ISSUE TITLE
rigid_scan_2_mesh_alignment(scan, mesh) very slow

### ISSUE THREAD

**Issue by sysuKaiYang** [soubhiksanyal/now_evaluation#4]
Hi, I am trying the NoW with the evaluation code. However, I generated the BFM shape model and landmarks from the validation image set, and pass them to the evaluation code. It shows something like this:

 5.60e+07 | dist: 5.60e+07 | s_reg: 0.00e+00
4.75e+07 | dist: 4.75e+07 | s_reg: 0.00e+00
2.92e+07 | dist: 2.92e+07 | s_reg: 0.00e+00
7.28e+06 | dist: 7.28e+06 | s_reg: 0.00e+00
3.22e+06 | dist: 3.22e+06 | s_reg: 0.00e+00
1.67e+06 | dist: 1.67e+06 | s_reg: 0.00e+00
4.79e+05 | dist: 4.79e+05 | s_reg: 0.00e+00
1.87e+05 | dist: 1.87e+05 | s_reg: 0.00e+00
1.15e+05 | dist: 1.15e+05 | s_reg: 0.00e+00
8.80e+04 | dist: 8.80e+04 | s_reg: 0.00e+00
7.32e+04 | dist: 7.32e+04 | s_reg: 0.00e+00

It takes a few minutes to print a new line of the above information but no result return.
Could you please help me with it?

**Comment by TimoBolkart** [comment]
Can you please check if your mesh get properly loaded?
As a simple test, pleas try to load the mesh file you have problems for, within an ipython by
```
from psbody.mesh import Mesh
mesh = Mesh(filename=mesh_filename)
print(mesh.v)
print(mesh.f)
```
Does that print the vertices and faces of the mesh?

You can also load and export a mesh using the Mesh package to see if loading is successful by:
`mesh.write_obj('FILENAME')`
followed by trying to open the resulting mesh in MeshLab.

**Comment by sysuKaiYang** [comment]
> Can you please check if your mesh get properly loaded?
> As a simple test, pleas try to load the mesh file you have problems for, within an ipython by
> 
> ```
> from psbody.mesh import Mesh
> mesh = Mesh(filename=mesh_filename)
> print(mesh.v)
> print(mesh.f)
> ```
> 
> Does that print the vertices and faces of the mesh?
> 
> You can also load and export a mesh using the Mesh package to see if loading is successful by:
> `mesh.write_obj('FILENAME')`
> followed by trying to open the resulting mesh in MeshLab.


I try to print the load mesh with command:
```
 predicted_mesh = Mesh(filename=predicted_mesh_path)
 print(predicted_mesh.v)
 print(predicted_mesh.f)
```
And the result is :
```
Processing 1 of 352 (FaMoS_180424_03335_TA, multiview_expressions, IMG_0053.jpg)
[[-0.548828  0.254775  0.625174]
 [ 0.288109  0.246847  0.263564]
 [-0.548114  0.252454  0.624971]
 ...
 [ 0.28755   0.247267  0.212343]
 [ 0.647362 -0.345341  0.051591]
 [ 0.282352  0.243812  0.210845]]
[[    0     1   130]
 [    0   130   129]
 [    1     2   130]
 ...
 [35706 27742 27704]
 [35707 35708 27742]
 [35708 27776 27742]]
```

I think the mesh is loaded successfully.

**Comment by sysuKaiYang** [comment]
Something strange I found when I try to save the original mesh to another file as you said with 
```
mesh.write_obj('FILENAME')
```

My original mesh *.obj is shown normally, but the new mesh saved with the above command is abnormal.


I obtained my original mesh with the command:
```
# save 3D face to obj file
def save_obj(path, v, f, c):
    with open(path, 'w') as file:
        for i in range(len(v)):
            file.write('v %f %f %f %f %f %f\n' % (v[i, 0], v[i, 1], v[i, 2], c[i, 0], c[i, 1], c[i, 2]))

        file.write('\n')

        for i in range(len(f)):
            file.write('f %d %d %d\n' % (f[i, 0], f[i, 1], f[i, 2]))

    file.close()
```
So is there any problem with the format of mesh?

**Comment by TimoBolkart** [comment]
Yes, the problem is the color appended to the vertices. The used Mesh package is unable to handle this. If you export it without the vertex colors, this should work.

**Comment by TimoBolkart** [comment]
I added some simple test to check the mesh loading and the rigid alignment

**Comment by sysuKaiYang** [comment]
Thanks for your suggestion. I remove the color in vertex and everything works fine.
