### ISSUE TITLE
Performing evaluation with DECA

### ISSUE THREAD

**Issue by danperazzo** [soubhiksanyal/now_evaluation#5]
Hello guys, thank you for releasing the code for your amazing research!
I have been trying to perform the allignment withe results obtained with the [DECA](https://github.com/YadiraF/DECA) technique.
However, I have stumbled into issues regarding the allignment with the ground-truth scans. 

We were using the landmarks available with the face model, however, they seem not to be the landmarks that you used during the evaluation for DECA> How did you manage to make the quantitative evaluation with deca and which landmarks did you use? Do you have any file on the vertices?

**Comment by TimoBolkart** [comment]
Hi, you are right, the now_evaluation only uses the subset of the overall landmarks (see [here](https://github.com/soubhiksanyal/now_evaluation/blob/main/landmarks_7_annotated.png) for details).
You can see the static landmarks for FLAME labeled [here](https://github.com/TimoBolkart/TF_FLAME/blob/master/data/landmarks_51_annotated.png), so you just use the landmarks with indices [19, 22, 25, 28, 16, 31, 37] as input to the now_evaluation. Does that answer your question?

**Comment by danperazzo** [comment]
Hello @TimoBolkart. Thank you! Another question, the now dataset only has scans with people in neutral expressions.
So, I supose that to perform the evaluation correctly I need to zero the expression and jaw pose coefficients in the FLAME model. Is that correct?

**Comment by TimoBolkart** [comment]
Hello @danperazzo, yes, we only have scans in neural expression, and again yes, using zeros for expression and jaw pose coefficients for FLAME, to evaluate the identity dependent shape only, is the way to go.

**Comment by danperazzo** [comment]
Thank you very much!
