### ISSUE TITLE
Performing evaluation with Deng et al

### ISSUE THREAD

**Issue by danperazzo** [soubhiksanyal/now_evaluation#6]
Hello guys, thanks again for releasing this benchmark! I have been trying to duplicate the results you obtained in the evaluation and I have stumbled into some issues.

The Deng et al technique uses a facial landmark extractor, we tried with dlib, however, in some cases it fails to extract landmarks. Did you use dlib or did you use another technique? 

And in cases that the landmark extractor failed, did your team eliminate the image from the evaluation proccess?

I tried to use dlib, it did not work on 70 images of the test set. We eliminated those images on the evaluation and the error we obtained was much higher than the reported on the evaluation set. We were trying to find the source of error.

Again, thank you for your attention!

**Comment by TimoBolkart** [comment]
We provide some bounding box for every image, for cases where the landmark detector fails, you can either use this box or try another detector. For the Deep3DFaceRecon_PyTorch of Deng et al., the original authors were running the evaluation and provided the meshes to us. Therefore, I don't know what they did to detect the faces, but they provided a result mesh for every image in the dataset.
